# Generated by Django 3.2.4 on 2021-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twotoken',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
