# Generated by Django 3.2.4 on 2021-06-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_alter_twotoken_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='bussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('category', models.CharField(choices=[('RESTURANT', 'Resturant'), ('PLUMBER', 'Plumber'), ('HOMESERVICE', 'Home Service')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
            ],
        ),
    ]
