# Generated by Django 3.2.4 on 2021-07-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_alter_bussiness_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='category',
            field=models.CharField(choices=[('RESTURANT', 'Resturant'), ('PLUMBER', 'Plumber'), ('HOMESERVICE', 'Home Service')], max_length=15),
        ),
    ]
